<?php

namespace AppBundle\Repository;

/**
 * JoinformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoinformRepository extends \Doctrine\ORM\EntityRepository
{
}
